//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpSigmaVenda.conexão
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensVenda
    {
        public int iditem { get; set; }
        public Nullable<int> idvenda { get; set; }
        public Nullable<int> idproduto { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<decimal> precoUnit { get; set; }
        public Nullable<decimal> precoTotal { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual venda venda { get; set; }
    }
}
