//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpSigmaVenda.conexão
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public int idvenda { get; set; }
        public int idproduto { get; set; }
        public int idusuario { get; set; }
        public int idcliente { get; set; }
        public decimal precoTotal { get; set; }
        public System.DateTime data { get; set; }
        public int quantidade { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
