//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpSigmaVenda.conexão
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venda()
        {
            this.ItensVenda = new HashSet<ItensVenda>();
        }
    
        public int idvenda { get; set; }
        public int idusuario { get; set; }
        public int idcliente { get; set; }
        public decimal precoTotal { get; set; }
        public System.DateTime data { get; set; }
        public string metodo_pagamento { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensVenda> ItensVenda { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
