USE [master]
GO

/****** Object:  Database [venda_produto]    Script Date: 24/10/2023 16:53:12 ******/
DROP DATABASE [venda_produto]
GO

/****** Object:  Database [venda_produto]    Script Date: 24/10/2023 16:53:12 ******/
CREATE DATABASE [venda_produto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'venda_produto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MICRO12\MSSQL\DATA\venda_produto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'venda_produto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MICRO12\MSSQL\DATA\venda_produto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [venda_produto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [venda_produto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [venda_produto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [venda_produto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [venda_produto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [venda_produto] SET ARITHABORT OFF 
GO

ALTER DATABASE [venda_produto] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [venda_produto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [venda_produto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [venda_produto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [venda_produto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [venda_produto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [venda_produto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [venda_produto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [venda_produto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [venda_produto] SET  ENABLE_BROKER 
GO

ALTER DATABASE [venda_produto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [venda_produto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [venda_produto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [venda_produto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [venda_produto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [venda_produto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [venda_produto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [venda_produto] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [venda_produto] SET  MULTI_USER 
GO

ALTER DATABASE [venda_produto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [venda_produto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [venda_produto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [venda_produto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [venda_produto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [venda_produto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [venda_produto] SET QUERY_STORE = OFF
GO

ALTER DATABASE [venda_produto] SET  READ_WRITE 
GO

